### ISSUE TITLE
Focus problems with gnome-shell 3.4

### ISSUE THREAD

**Issue by pavlos256** [paulrouget/firefox-jsterm#10]
There's a strange focus problem on my system and it's unusable.

For example, I hit Shift+F2, the toolbar appears, I type "help", hit enter and then I see something flash, it disappears and Firefox has lost focus.

Trying something that doesn't exist is even worse: I type the letters

> > t
> > te
> > tes

once I hit the 's', something flashses, the toolbar and firefox loose focus and even if I click there again the focus is automatically lost again. At that point I'm unable to even use backspace to delete "tes".

I don't know if this is a problem with jsterm, Firefox, Gnome-Shell or a combination of these. There have been some weird focus problems with Gnome-Shell 3.4 and Guake as well, see: http://guake.org/ticket/436

**Comment by paulrouget** [comment]
Firefox and Gnome bug: https://bugzilla.mozilla.org/show_bug.cgi?id=771169
