### ISSUE TITLE
Navigation between control elements

### ISSUE THREAD

**Issue by mrpollo** [paulrouget/firefox-jsterm#11]
**This is a feature request more than a bug.**

Navigation between the control elements can be a useful way of moving around between the JSTerm and the Web Console.
### Example 1.

Game canvas with resize event captured, on the JSTerm you change the window size **"resize to 300 300"** then you want to move to the Web Console to check on your variables, right now you can only do **"console open"** assuming its not already open, on which your only option is to click on the web console input field.
#### Image 1

![Example 1 - Image 1](https://dl.dropbox.com/u/9694286/jsterm/Screen%20Shot%202012-07-20%20at%201.19.20%20PM.png)
#### Image 2

![Example 1 - Image 2](https://dl.dropbox.com/u/9694286/jsterm/Screen%20Shot%202012-07-20%20at%201.19.40%20PM.png)
### Example 2.

Again related to resize, once you resized you decide you want to change some properties on the **<body>** of your html so you open the inspector  **"inspect body"** if focus was passed to the style inspector we could potentially write the rules with the keyboard then navigate back to the JSTerm to either close the inspector and keep resizing or do another changes
#### Image 1

![Example 2 - Image 1](https://dl.dropbox.com/u/9694286/jsterm/Screen%20Shot%202012-07-20%20at%201.32.59%20PM.png)
## Proposed key bindings:

a combination of either this could work

Move forward: **Command + option + ]**
Move backwards: **Command + option + [**

**Comment by paulrouget** [comment]
You're confused. What you call JSTerm is Firefox Command Line (gcli).
This is a GCLI bug (Firefox code). Please report the bug here: http://is.gd/RpVsee

**Comment by mrpollo** [comment]
Thanks and sorry for the confusion
