### ISSUE TITLE
Ctrl+W doesn't work correctly

### ISSUE THREAD

**Issue by toupeira** [paulrouget/firefox-jsterm#14]
It does delete a word, but when you continue typing the word reappears and the new characters are inserted after it.

I'm using Iceweasel 16.0a2 with Xfce on Debian, I think the Ctrl+W actually comes from Gtk and me having Emacs keys enabled.

**Comment by paulrouget** [comment]
Does it happen in the Scratchpad as well?

**Comment by toupeira** [comment]
Well possibly, I can't really check since Ctrl+W also closes the Scratchpad
;-)

On 23 July 2012 21:35, Paul Rouget <
reply@reply.github.com

**Comment by paulrouget** [comment]
Can you try with the Style Editor then?

**Comment by toupeira** [comment]
The Style Editor gets closed as well. FWIW Ctrl+W works fine in the
standard JS Console, but I guess that interface is implemented differently.

On 23 July 2012 22:13, Paul Rouget <
reply@reply.github.com

**Comment by aL3xa** [comment]
Linux user here (ArchLinux + awesomewm + FF Nightly). I've set Emacs keybindings in `.gtkrc`. This happens both in Scratchpad and JSTerm. Very frustrating, as I have [KeySnail](https://github.com/mooz/keysnail/) installed and I'm really hooked on Emacs keybindings in general. Even when I try to do `C-Backspace` to delete last word, whole line is blanked and after I start typing, the word reappears.

I read somewhere that this whole Scratchpad interface was _borrowed_ from Eclipse. It'd be nice if you could keep it compatible with GTK container Firefox relies on.
