### ISSUE TITLE
Show "null" evaluations

### ISSUE THREAD

**Issue by harthur** [paulrouget/firefox-jsterm#22]
A statement that evaluates to `undefined` or `null` won't output anything. It might be hard to tell what's going on:

actual:

``` javascript
var x = document.getElementById("container");
x;
6; // 6
```

expected:

``` javascript
var x = document.getElementById("container");
x; // null
6; // 6
```

It is annoying to see the `undefined` after a declaration. Maybe it could just show if it's `null`?

**Comment by paulrouget** [comment]
fixed (commit 69b7634)
