### ISSUE TITLE
JS Term "$ "is overiding jQuery

### ISSUE THREAD

**Issue by nhunzaker** [paulrouget/firefox-jsterm#27]
I tried to open a static html file and recieved an error that a jQuery method was undefined, upon further research it looks like the $ namespace is being overridden by JSTerm :(.

```
> $
(function JSTH_$(aSelector)
  {
    "use strict";

    return aJSTerm.window.document.querySelector(aSelector);
})
```

This is actually really frustrating, any thoughts on this?

**Comment by paulrouget** [comment]
Right. Before adding functions to the sandbox, we should make sure the properties are not already defined.

**Comment by keeguon** [comment]
Any chances of this getting fixed one way or another...?
