### ISSUE TITLE
Keyboard navigation to inspect last object

### ISSUE THREAD

**Issue by harthur** [paulrouget/firefox-jsterm#29]
I'm always switching from typing to using the mouse to click on objects to inspect them. A keyboard shortcut to access the last  object would be sweet, and maybe it could focus the filter input.

**Comment by valueof** [comment]
What about `:obj` to inspect `obj`? Scratchpad-like cmd-I works as well.

**Comment by paulrouget** [comment]
`:inspect obj` ?

**Comment by sent-hil** [comment]
+1 for `:inspect`.

**Comment by anthonyringoet** [comment]
+1
