### ISSUE TITLE
Doesn't work with FF 18

### ISSUE THREAD

**Issue by artlantis** [paulrouget/firefox-jsterm#32]
I installed on FF 18 edition but the console screen empty as well as can't write something.

**Comment by blissdev** [comment]
This is a duplicate of #31. Seems like dev responsiveness is a bit slow at the moment. I've started to look at the issue, but I'm a bit out of my depth.

**Comment by artlantis** [comment]
Same issue, but button bar doesn't show in FF18 as well!
