### ISSUE TITLE
jsterm 2.3 fails to load

### ISSUE THREAD

**Issue by jeffgca** [paulrouget/firefox-jsterm#35]
When I install JSterm 2.3 on Aurora 20 and Nightly 21, I get these warnings:

Timestamp: 2013-01-31 10:28:52 AM
Warning: WARN addons.xpi: Error loading bootstrap.js for jsterm@paulrouget.com: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIStringBundle.GetStringFromName]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/jeff/Library/Application%20Support/Firefox/Profiles/b49h24eg.default/extensions/jsterm@paulrouget.com.xpi!/bootstrap.js :: <TOP_LEVEL> :: line 19"  data: no]
Source File: resource://gre/modules/XPIProvider.jsm -> jar:file:///Users/jeff/Library/Application%20Support/Firefox/Profiles/b49h24eg.default/extensions/jsterm@paulrouget.com.xpi!/bootstrap.js
Line: 19

Timestamp: 2013-01-31 10:30:44 AM
Warning: WARN addons.xpi: Exception running bootstrap method startup on jsterm@paulrouget.com: TypeError: toolDefinition is undefined
Source File: resource:///modules/devtools/gDevTools.jsm
Line: 69

The jsterm tab doesn't show up in the devtools panel:

![jsterm-missing](https://f.cloud.github.com/assets/104315/115581/89201590-6bd4-11e2-9733-a0f32c706c52.png)

**Comment by paulrouget** [comment]
Can you restart Firefox and tell me if it fixes the problem?

**Comment by jeffgca** [comment]
Re-starting Firefox fixes the problem.

**Comment by paulmillr** [comment]
cannot reproduce, seems it was fixed.
