### ISSUE TITLE
Please put style rules in chrome://../skin/

### ISSUE THREAD

**Issue by alfredkayser** [paulrouget/firefox-jsterm#38]
Firefox Terminal V3 is a nice extension!
I have one small request though:
Can chrome://jsterm/content/orion.css be replaced with chrome://jsterm/skin/orion.css?
This allows themers such as me to style the terminal in the same style as the other window/devtool parts in "full themes".

**Comment by paulmillr** [comment]
sure, why not. mind submitting a pull request?
