### ISSUE TITLE
"No restart"

### ISSUE THREAD

**Issue by sole** [paulrouget/firefox-jsterm#40]
Hi!

Just installed this extension to try it out. However, I found something slightly confusing; not sure if that's something you can fix or if it's something to do with the Add-ons site.

Generally we always have to restart Firefox in order to get an add-on working. But in this case I got this beautiful and promising "No restart" sticker close to the title:
![Screen shot 2013-03-21 at 08 50 24](https://f.cloud.github.com/assets/5609/284884/f5a6c820-9204-11e2-857a-de44f2490804.png)

This got me superexcited as having to restart my browser always makes me delay the restart until I have finished with everything I was doing/reading/etc--so it could well be that I forget that I install the add-on and only remember about it like three days later.

Anyway, I installed it, and opened dev tools, and... nothing, JSTerm wasn't there.

I effectively had to restart the browser. Then I opened the dev tools and finally the terminal was there. I am using Firefox 20 (beta channel).

Thanks for the extension!

**Comment by webmatze** [comment]
Yes I experienced the same. Had to restart Firefox.

**Comment by maks** [comment]
This is still an issue on Firefox 21 - didn't see the JSTerm entry on dev tools until after a restart.
