### ISSUE TITLE
Switching to coffee script doesn't work

### ISSUE THREAD

**Issue by flosse** [paulrouget/firefox-jsterm#42]
The behavior of version 2.4 is:

``` javascript
:coffee // error: SyntaxError: syntax error
```

**Comment by paulmillr** [comment]
actual version should be 3.0. @paulrouget any idea why MDN has old?

**Comment by flosse** [comment]
ok, installing from github works fine :)

**Comment by ur5us** [comment]
@paulrouget Any chance that you update the version on MDN?
