### ISSUE TITLE
Incompatible with FF 25

### ISSUE THREAD

**Issue by piotrex** [paulrouget/firefox-jsterm#45]
![screenshot](http://i.imgur.com/3S2ftY4.png)

Errors:

```
Error: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
Source file: chrome://jsterm/content/jsterm.js
Line: 4
```

```
Error: TypeError: iframeWindow.JSTermUI is undefined
Source file: resource://gre/modules/XPIProvider.jsm -> jar:file:///E:/Piotrek/pliki%20program%C3%B3w/FirefoxDeveloper/Data/profile/extensions/jsterm@paulrouget.com.xpi!/bootstrap.js
Line: 34
```

```
Error: TypeError: JSTermUI is undefined
Source file: chrome://jsterm/content/jsterm.xul
Line: 1
```

**Comment by flosse** [comment]
I've got the same problem

**Comment by paulmillr** [comment]
Unfortunately i'm not sure what happens here.

> Error: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]

This error can be fixed by applying this patch:

``` diff
--- a/chrome/jsterm.js
+++ b/chrome/jsterm.js
@@ -1,7 +1,8 @@
 let Cu = Components.utils;
 let Ci = Components.interfaces;
+let devtools = Cu.import("resource://gre/modules/devtools/Loader.jsm", {}).devtools;
 Cu.import("resource:///modules/source-editor.jsm");
-Cu.import("resource://gre/modules/devtools/WebConsoleUtils.jsm");
+devtools.require('devtools/toolkit/webconsole/utils')
```

but after that nothing happens when you select jsterm tab. No logs, no errors, nothing @paulrouget ?

**Comment by paulrouget** [comment]
Sorry, not actively looking at this as we're in the process of integrating JSTerm in Firefox.
Also, we changed many internal things in Firefox 27. JSTerm will get even more broken and unmaintainable as an addon.

I suggest that you wait until https://bugzilla.mozilla.org/show_bug.cgi?id=911456 gets fixed (we are actively working on that, but not sure yet when it's gonna land).

**Comment by paulmillr** [comment]
@paulrouget does it mean firefox will natively support coffee script in console?

**Comment by paulrouget** [comment]
Not Firefox. But the built-in JSTerm will be able to do so (not the v1 though).

**Comment by KnightYoshi** [comment]
You should add to the description of the add-on that it's being integrated natively and that support for the add-on has been dropped. That would have prevented my confusion (and I'm sure the confusion of others) of why it wasn't working.

**Comment by paulmillr** [comment]
done

**Comment by flosse** [comment]
@paulmillr  on https://addons.mozilla.org/ I still can read `Works with Firefox 20.0a1 - 26.`

...and do you know any alternatives that support CoffeeScript? Or what would you recommend for FF 25 and FF 26 users?

**Comment by paulmillr** [comment]
I don't know any

**Comment by vkz** [comment]
@paulrouget is Mozilla no longer pursuing this? jsTerm doesn't appear to work, nor has it been integrated into dev tools. Thanks
