### ISSUE TITLE
Objects should be recognized on its own

### ISSUE THREAD

**Issue by poke** [paulrouget/firefox-jsterm#9]
When entering an object on its own, JSTerm does not recognize the object syntax and shows an error instead. As a REPL it should recognize the object and simply return it.

```
{ a: 'b', c: 'd' } // error: SyntaxError: invalid label
```

Compare this with Node’s behaviour which is the correct one:

```
> { a: 'b', c: 'd' }
{ a: 'b', c: 'd' }
```

**Comment by paulrouget** [comment]
Well, in theory, when you write this, it's supposed to be a label declaration. But the theory feels wrong here :)
